# Generated by Django 4.2.5 on 2023-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
